const crypto = require('crypto');
const QRCode = require('qrcode');
const bwipjs = require('bwip-js');
const { ZipArchive } = require('archiver');
const fs = require('fs');
const path = require('path');

const CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

/**
 * Generates one random 7-character alphanumeric string (upper+lower+digit),
 * using crypto.randomInt for real randomness rather than Math.random.
 */
const randomSevenChars = () => {
  let result = '';
  for (let i = 0; i < 7; i++) {
    result += CHARSET[crypto.randomInt(0, CHARSET.length)];
  }
  return result;
};

/**
 * Generates `count` UNIQUE barcode IDs for one hand category, each in the
 * format "<7 random chars>-<numberOfHands>". Uniqueness is enforced within
 * this batch via a Set, regenerating on the (extremely rare, ~1 in 3.5
 * trillion) collision.
 */
const generateBarcodeIds = (numberOfHands, count) => {
  const seen = new Set();
  const ids = [];
  let attempts = 0;
  const maxAttempts = count * 20; // generous safety margin against collisions

  while (ids.length < count) {
    attempts++;
    if (attempts > maxAttempts) {
      throw new Error(
        `Could not generate ${count} unique barcode IDs for ${numberOfHands} hands after ${maxAttempts} attempts`
      );
    }
    const candidate = `${randomSevenChars()}-${numberOfHands}`;
    if (!seen.has(candidate)) {
      seen.add(candidate);
      ids.push(candidate);
    }
  }

  return ids;
};

/**
 * Builds ONE sticker as an SVG string: QR code (top-left) + large hand
 * number (top-right) + barcode (bottom, full width) + the barcode ID as
 * small text underneath it, matching the reference photo's layout.
 *
 * qrPngBase64 is the SAME for every sticker in a category (same QR per
 * hand category, per spec) — caller generates it once and passes it in,
 * rather than regenerating per sticker.
 */
const buildStickerSVG = async (qrPngBase64, numberOfHands, barcodeId) => {
  const width = 500;
  const height = 320;
  const qrSize = 200;
  const padding = 20;

  const barcodeSvg = bwipjs.toSVG({
    bcid: 'code128',
    text: barcodeId,
    scale: 2,
    height: 10,
    includetext: false,
  });

  // Strip the outer <svg ...> wrapper from bwip's output so we can nest its
  // inner content inside our own <g> at a controlled position/size.
  const innerMatch = barcodeSvg.match(/<svg[^>]*viewBox="([^"]*)"[^>]*>([\s\S]*)<\/svg>/);
  const barcodeViewBox = innerMatch ? innerMatch[1] : '0 0 268 58';
  const barcodeInner = innerMatch ? innerMatch[2] : '';

  const barcodeAreaWidth = width - padding * 2;
  const barcodeAreaHeight = 70;
  const barcodeY = qrSize + padding * 2 + 10;

  return `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${width}" height="${height}" fill="#ffffff" />
  <rect x="1" y="1" width="${width - 2}" height="${height - 2}" fill="none" stroke="#d1d5db" stroke-width="2" />
  <image x="${padding}" y="${padding}" width="${qrSize}" height="${qrSize}" href="data:image/png;base64,${qrPngBase64}" />
  <text x="${padding * 2 + qrSize + (width - padding - (padding * 2 + qrSize)) / 2}" y="${qrSize / 2 + padding + 20}" font-family="sans-serif" font-weight="bold" font-size="130" text-anchor="middle" fill="#000000">${numberOfHands}</text>
  <svg x="${padding}" y="${barcodeY}" width="${barcodeAreaWidth}" height="${barcodeAreaHeight}" viewBox="${barcodeViewBox}" preserveAspectRatio="none">
    ${barcodeInner}
  </svg>
  <text x="${width / 2}" y="${barcodeY + barcodeAreaHeight + 20}" font-family="monospace" font-size="18" text-anchor="middle" fill="#000000">${barcodeId}</text>
</svg>`;
};

/**
 * Generates all sticker SVGs for ONE hand category and writes them into a
 * ZIP file on disk. barcodeIds must be pre-generated by the caller (see
 * records_services.js buildQrCodes) — this function does NOT generate new
 * IDs, so re-downloading a ZIP never changes which barcodeIds exist.
 *
 * outputDir must already exist (caller's responsibility).
 */
const generateCategoryZip = async ({ numberOfHands, qrUniqueId, brandName, packageDate, outputDir, barcodeIds }) => {
  const qrPngBuffer = await QRCode.toBuffer(qrUniqueId, { width: 200, margin: 1 });
  const qrPngBase64 = qrPngBuffer.toString('base64');

  const dateStr = new Date(packageDate).toISOString().slice(0, 10); // YYYY-MM-DD
  const safeBrand = brandName.replace(/\s+/g, ''); // "Hi Banana" -> "HiBanana"
  const zipFilename = `${numberOfHands}Hand_${dateStr}_${safeBrand}.zip`;
  const zipPath = path.join(outputDir, zipFilename);

  await new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = new ZipArchive({ zlib: { level: 9 } });

    output.on('close', resolve);
    archive.on('error', reject);
    archive.pipe(output);

    (async () => {
      for (let i = 0; i < barcodeIds.length; i++) {
        const svg = await buildStickerSVG(qrPngBase64, numberOfHands, barcodeIds[i]);
        archive.append(svg, { name: `${barcodeIds[i]}.svg` });
      }
      archive.finalize();
    })().catch(reject);
  });

  return { zipFilename, zipPath, barcodeIds };
};

module.exports = {
  generateBarcodeIds,
  buildStickerSVG,
  generateCategoryZip,
};