import { useState } from 'react';
import { resolveScan } from '../../services/scanningService';

export default function Scanner() {
  const [code,setCode]=useState(''); const [result,setResult]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(e)=>{e.preventDefault();setError('');setResult(null);setBusy(true);try{setResult((await resolveScan(code)).data);}catch(err){setError(err.response?.data?.message||err.message);}finally{setBusy(false);}};
  return <section><div className="mb-6"><p className="text-sm font-semibold text-orange-600">SCANNING</p><h2 className="text-3xl font-bold text-slate-900">Resolve QR / Barcode</h2><p className="mt-2 text-slate-500">Paste the value produced by a scanner. QR values are MongoDB category IDs; barcodes use the stored sticker barcode ID.</p></div><form onSubmit={submit} className="flex max-w-2xl flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row"><input autoFocus value={code} onChange={(e)=>setCode(e.target.value)} placeholder="Scan or paste code" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3.5 py-3 outline-none focus:ring-2 focus:ring-orange-100"/><button disabled={busy||!code.trim()} className="rounded-lg bg-orange-500 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?'Checking...':'Resolve'}</button></form>{error&&<div className="mt-4 max-w-2xl rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{result&&<ResultCard data={result}/>}</section>;
}
function ResultCard({data}){const rows=[['Type',data.type?.toUpperCase()],['Brand',data.brandName],['Package Date',new Date(data.packageDate).toLocaleDateString()],['Line Number',data.lineNumber],['Vendor',data.vendorName],['Farmer',data.farmerName],['Supervisor',data.supervisor],['Weight',`${data.weight} kg`],['Hands',data.numberOfHands],['Category Quantity',data.quantity],['QR Unique ID',data.qrUniqueId],['Barcode ID',data.barcodeId||'—'],['Address',data.address],['Coordinates',`${data.geolocation?.latitude}, ${data.geolocation?.longitude}`]];return <div className="mt-5 max-w-3xl rounded-xl border border-green-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-green-500"></span><h3 className="font-bold text-slate-900">Record found</h3></div><dl className="grid gap-x-8 gap-y-3 sm:grid-cols-2">{rows.map(([k,v])=><div key={k}><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{k}</dt><dd className="mt-0.5 break-all text-sm font-medium text-slate-800">{v}</dd></div>)}</dl></div>;}
